[package]
name = "generic-card-game"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcadeum = { git = "ssh://git@github.com/horizon-games/arcadeum-state.git", tag = "0.12.3", features = ["tester"] }
